import {initializeApp} from 'firebase/app';
import {getAuth,onAuthStateChanged,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendEmailVerification,sendPasswordResetEmail,signOut,reload,getIdToken,GoogleAuthProvider,signInWithPopup,connectAuthEmulator} from 'firebase/auth';
import {getFirestore,doc,getDocFromServer,runTransaction,serverTimestamp,collection,query,orderBy,limit,startAfter,getDocs,connectFirestoreEmulator} from 'firebase/firestore';
import {OWNER_EMAIL,AVATARS,CHAPTERS,clean,merge,totals,fromGame,toGame} from './model.js';
import {firebaseConfig,accountsEnabled} from './config.js';

const emulator=location.hostname==='localhost'&&location.port==='4319';
const enabled=accountsEnabled||emulator;
const app=initializeApp(emulator?{...firebaseConfig,projectId:'demo-mathcraft',apiKey:'demo-key'}:firebaseConfig);
const auth=getAuth(app),db=getFirestore(app);
if(emulator){connectAuthEmulator(auth,'http://127.0.0.1:9099',{disableWarnings:true});connectFirestoreEmulator(db,'127.0.0.1',8080);}
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let user=null,row=null,ready=!enabled,loading=false,generation=0,pending=clean(),queue=Promise.resolve(),timer=null,saveError='',authBusy=false,adminRows=[],cursor=null,hasMore=false,adminLoaded=false,adminLoading=false;
let guest=window.MCBridge.export();
const isAdmin=()=>user?.emailVerified&&user.email?.toLowerCase()===OWNER_EMAIL;
const accountRoute=()=>['login','register','profile','admin','forgot'].includes(location.hash.slice(1));
const originalRoute=window.route;
const bar=document.createElement('div');bar.className='account-bar';document.querySelector('header').after(bar);
const status=(message)=>{if($('account-message'))$('account-message').textContent=message;};
function header(){bar.innerHTML=`<span>${!ready?'Checking your account…':user?`${esc(row?.avatar||'🌱')} ${esc(row?.nickname||'Learner')} · ${saveError?'Save needs attention':loading?'Loading profile…':'Personal progress'}`:'Playing as a guest · points stay on this device'}</span><div>${user?'<a href="#profile">My profile</a>':'<a href="#login">Log in</a><a href="#register">Create account</a>'}<a href="#admin">Admin</a></div>`;}
function messageBox(){return '<p id="account-message" role="status" aria-live="polite"></p>';}
function stopLessons(){window.L2?.stopActivity();window.L3?.stopActivity();if('speechSynthesis'in window)speechSynthesis.cancel();}
function shell(title,body){stopLessons();$('score').textContent=user&&row?`◆ ${totals(pending).gems} gems · Your profile`:'Your account';$('main').innerHTML=`<p class="eyebrow">MATHCRAFT · YOUR ACCOUNT</p><h1>${title}</h1>${body}`;}
function failure(e){const code=e?.code||'';return ({'auth/invalid-credential':'The email or password did not match. Try again, or reset your password.','auth/email-already-in-use':'This email already has an account. Log in or reset your password.','auth/weak-password':'Choose a password with at least 12 characters.','auth/invalid-email':'Enter a complete email address.','auth/too-many-requests':'Too many attempts. Please wait a few minutes and try again.','auth/network-request-failed':'Could not connect. Check your internet connection and try again.','auth/popup-closed-by-user':'The Google window was closed. You can try again.','auth/popup-blocked':'Allow the Google sign-in window, then try again.','auth/unauthorized-domain':'Sign-in is not yet enabled for this website address.','auth/operation-not-allowed':'This sign-in method still needs to be enabled in Firebase.','permission-denied':'Firebase has not allowed this account to access the saved profile. Please contact the site owner.','unavailable':'Could not reach the progress database. Check your connection and retry.'})[code]||'That did not finish. Please retry. Your password has not been displayed or stored by this page.';}
function renderLogin(mode){const admin=mode==='admin',signup=mode==='register',forgot=mode==='forgot';
 shell(admin?'Admin login':signup?'Start your own adventure':forgot?'Reset your password':'Welcome back',`<div class="account-layout"><section class="panel account-form"><h2>${admin?'For the site owner':signup?'Create a learner account':forgot?'Get a reset link':'Keep your gems together'}</h2><p>${admin?'Sign in with your verified owner account. Other accounts cannot open the dashboard.':signup?'Ask a grown-up to help. Choose a nickname instead of your full name. Each learner needs a separate email account.':'Your progress follows you across devices when you sign in.'}</p>${!enabled?'<p class="account-warning">Account setup is being completed. You can keep exploring as a guest.</p>':''}<form id="account-form">${signup?'<label>Nickname<input name="nickname" autocomplete="nickname" maxlength="24" required placeholder="For example, Star Explorer"></label>':''}<label>Email address<input name="email" type="email" autocomplete="email" required ${admin?`value="${OWNER_EMAIL}"`:''}></label>${forgot?'':`<label>Password<input name="password" type="password" autocomplete="${signup?'new-password':'current-password'}" ${signup?'minlength="12"':''} required></label>${signup?'<small>Use at least 12 characters. Keep your password private.</small>':''}`}<button class="primary" ${!enabled?'disabled':''}>${forgot?'Send reset link':signup?'Create my account':admin?'Log in as admin':'Log in'}</button></form>${!forgot?`<button class="secondary" id="google-login" ${!enabled?'disabled':''}>Continue with Google</button>`:''}${messageBox()}<div class="account-links">${signup?'<a href="#login">Already registered? Log in</a>':'<a href="#register">Create a learner account</a>'}<a href="#forgot">Forgot password?</a><a href="#levels">Explore as a guest</a></div></section><section class="panel account-benefits"><span class="account-orbit">🌱</span><h2>A little more each day.</h2><p>Keep your gems, revisit your chapters and see how far you’ve come.</p><ul><li>106 missions across three levels</li><li>One personal progress profile</li><li>Hints and explanations whenever you need them</li></ul><p class="muted">We save your email, chosen nickname, progress and basic learning activity. Only you and the site owner can see your profile. We do not need your birthday, school or address.</p></section></div>`);
 $('account-form').onsubmit=async event=>{event.preventDefault();if(authBusy||!enabled)return;authBusy=true;const form=new FormData(event.currentTarget);const email=String(form.get('email')).trim();status('Connecting…');try{if(forgot){await sendPasswordResetEmail(auth,email,{url:location.origin+'/#login'});status('If an account exists for this email, a password reset link will arrive. Check your spam folder too.');}else if(signup){sessionStorage.setItem('mathcraft-new-nickname',String(form.get('nickname')).trim().slice(0,24));const result=await createUserWithEmailAndPassword(auth,email,String(form.get('password')));await sendEmailVerification(result.user,{url:location.origin+'/#profile'});location.hash='profile';render();}else{await signInWithEmailAndPassword(auth,email,String(form.get('password')));location.hash=admin?'admin':'profile';}}catch(e){status(failure(e));}finally{authBusy=false;}};
 if($('google-login'))$('google-login').onclick=async()=>{if(authBusy)return;authBusy=true;status('Opening Google sign-in…');try{await signInWithPopup(auth,new GoogleAuthProvider());location.hash=admin?'admin':'profile';}catch(e){status(failure(e));}finally{authBusy=false;}};
}
function verification(){shell('Check your email',`<section class="panel account-form"><h2>One more step</h2><p>Open the verification link sent to <strong>${esc(user.email)}</strong>, then come back here. This protects your saved progress.</p><button class="primary" id="verified">I have verified my email</button><button class="secondary" id="resend">Send another verification email</button><button class="quiet" id="logout">Log out</button>${messageBox()}</section>`);$('verified').onclick=async()=>{try{await reload(auth.currentUser);await getIdToken(auth.currentUser,true);if(!auth.currentUser.emailVerified){status('The email has not been verified yet. Open the link in your inbox first.');return;}await session(auth.currentUser);}catch(e){status(failure(e));}};$('resend').onclick=async()=>{try{await sendEmailVerification(auth.currentUser,{url:location.origin+'/#profile'});status('Verification email sent. Check your inbox and spam folder.');}catch(e){status(failure(e));}};$('logout').onclick=logout;}
function metrics(value){const t=totals(value);return `<div class="account-metrics"><section><strong>${t.gems}</strong><span>gems earned</span></section><section><strong>${t.completed}<small> / 106</small></strong><span>missions completed</span></section><section><strong>${clean(value).visited.length}<small> / 22</small></strong><span>chapters opened</span></section></div>`;}
function profile(){shell('Your adventure, saved',`${metrics(pending)}<div class="account-layout"><section class="panel account-form"><h2>${esc(row.avatar)} ${esc(row.nickname)}</h2><p>${esc(user.email)}</p><form id="profile-form"><label>Nickname<input name="nickname" value="${esc(row.nickname)}" maxlength="24" required autocomplete="nickname"></label><label>Choose your explorer<select name="avatar">${AVATARS.map(v=>`<option ${v===row.avatar?'selected':''}>${v}</option>`).join('')}</select></label><button class="primary">Save profile</button></form>${messageBox()}${saveError?'<p class="account-warning">Your latest progress is waiting to save. Keep this device open and retry.</p><button id="retry-save">Retry saving</button>':'<p class="muted">Progress is saved automatically. Repeating a mission does not add extra gems.</p>'}<button class="secondary" id="reset-password">Email me a password reset link</button><button class="quiet" id="logout">Log out safely</button></section><section class="panel"><h2>Your three levels</h2>${[50,32,24].map((max,i)=>`<a class="level-progress" href="#level${i+1}"><span>Level ${i+1}</span><strong>${totals(pending).levels[i]} / ${max}</strong><progress value="${totals(pending).levels[i]}" max="${max}"></progress></a>`).join('')}<p>Pick up where you left off. Your saved gems belong to this account.</p>${isAdmin()?'<a class="primary" href="#admin">Open admin dashboard →</a>':''}</section></div>`);$('profile-form').onsubmit=async e=>{e.preventDefault();const form=new FormData(e.currentTarget),nickname=String(form.get('nickname')).trim();if(!nickname){status('Choose a nickname with at least one letter or symbol.');return;}try{await flush({nickname,avatar:String(form.get('avatar'))});if(location.hash==='#profile'){profile();status('Your profile has been saved.');}}catch(e){status(failure(e));}};$('reset-password').onclick=async()=>{try{await sendPasswordResetEmail(auth,user.email,{url:location.origin+'/#login'});status('Password reset email sent.');}catch(e){status(failure(e));}};$('logout').onclick=logout;if($('retry-save'))$('retry-save').onclick=async()=>{try{await flush();profile();}catch(e){status(failure(e));}};}
async function logout(){status('Saving your latest progress before logging out…');try{if(row)await flush();await signOut(auth);location.hash='login';}catch(e){status('Your progress has not finished saving. Check your connection and retry logging out.');}}
function apply(value,reset=true){window.MCBridge.load(toGame(value),reset);}
function cached(){const read=(key,fallback)=>{try{return JSON.parse(window.MCStore.getItem(key))||fallback;}catch{return fallback;}};return fromGame({l1:read('mathcraft-v1',{solved:{},lessons:{}}),l2:read('mathcraft-level2',{}),l3:read('mathcraft-level3',{})});}
function remember(){const g=toGame(pending);for(const [key,v]of [['mathcraft-v1',g.l1],['mathcraft-level2',g.l2],['mathcraft-level3',g.l3]]){try{localStorage.setItem(`mathcraft-account:${user.uid}:${key}`,JSON.stringify(v));}catch{saveError='Device storage is unavailable. Keep this page open until cloud saving finishes.';}}}
function flush(profileChange={},newSession=false){if(!user?.emailVerified||!row)return Promise.resolve();clearTimeout(timer);const uid=user.uid,gen=generation,value=clean(pending);const task=async()=>{if(gen!==generation)return;try{const next=await runTransaction(db,async tx=>{const ref=doc(db,'learners',uid),snap=await tx.get(ref);if(gen!==generation||auth.currentUser?.uid!==uid)throw new Error('Account changed');const old=snap.exists()?snap.data():row;const merged=merge(old,value);const next={...old,...merged,...profileChange,lastActive:serverTimestamp(),sessions:(old.sessions||0)+(newSession?1:0)};tx.set(ref,next);return next;});if(gen!==generation)return;row=next;pending=merge(pending,next);apply(pending,false);saveError='';header();}catch(e){if(gen===generation){saveError=failure(e);header();}throw e;}};queue=queue.catch(()=>{}).then(task);return queue;}
async function session(nextUser){if(!user&&ready)guest=window.MCBridge.export();const gen=++generation;clearTimeout(timer);stopLessons();user=nextUser;row=null;pending=clean();adminRows=[];cursor=null;adminLoaded=false;adminLoading=false;saveError='';window.MCStore.owner=user?.uid||null;apply({});ready=true;loading=!!user?.emailVerified;header();render();if(!user){window.MCBridge.load(guest);render();return;}if(!user.emailVerified){loading=false;render();return;}try{const local=cached(),ref=doc(db,'learners',user.uid);const snap=await getDocFromServer(ref);if(gen!==generation)return;row=snap.exists()?snap.data():{email:user.email,nickname:(sessionStorage.getItem('mathcraft-new-nickname')||'Explorer').trim().slice(0,24)||'Explorer',avatar:'🌱',...clean(),sessions:0,createdAt:serverTimestamp(),lastActive:serverTimestamp()};sessionStorage.removeItem('mathcraft-new-nickname');pending=merge(row,local);apply(pending);await flush({},true);if(gen!==generation)return;loading=false;header();render();}catch(e){if(gen!==generation)return;loading=false;row=null;saveError=failure(e);render();}}
function chapterRows(){const catalog=window.MCBridge.catalog();return catalog.map(c=>{const count=adminRows.reduce((n,r)=>n+c.ids.filter(id=>clean(r)[c.key].includes(id)).length,0),max=adminRows.length*c.ids.length;return `<div class="chapter-stat"><span>Level ${c.level} · ${esc(c.title)}</span><progress max="${max||1}" value="${count}"></progress><strong>${count} / ${max}</strong></div>`;}).join('');}
function admin(){if(!isAdmin()){shell('Admin access only','<section class="panel"><h2>This is a learner account</h2><p>You can manage your own profile. Only the verified site owner account can view usage across learners.</p><a href="#profile">Go to my profile</a></section>');return;}shell('Learning at a glance',`<p class="muted">Owner dashboard · ${esc(user.email)}. Only verified accounts that have opened the app appear here. Guest activity is not collected.</p><div id="admin-content"><p>Loading learner activity…</p></div>${messageBox()}<div class="actions"><button class="secondary" id="refresh-admin">Refresh analytics</button><a href="#profile">My profile</a></div>`);$('refresh-admin').onclick=()=>loadAdmin(true);if(adminLoaded)paintAdmin();else loadAdmin(true);}
async function loadAdmin(reset=false){if(!isAdmin()||adminLoading)return;adminLoading=true;const gen=generation;try{const q=query(collection(db,'learners'),orderBy('createdAt','desc'),...(reset||!cursor?[]:[startAfter(cursor)]),limit(100));const result=await getDocs(q);if(gen!==generation||!isAdmin())return;adminRows=reset?result.docs.map(d=>({...d.data(),uid:d.id})):[...adminRows,...result.docs.map(d=>({...d.data(),uid:d.id}))];cursor=result.docs.at(-1)||cursor;hasMore=result.size===100;adminLoaded=true;if(location.hash==='#admin')paintAdmin();}catch(e){if(gen===generation)status(failure(e));}finally{if(gen===generation)adminLoading=false;}}
function paintAdmin(){const now=Date.now(),active=adminRows.filter(r=>now-(r.lastActive?.toMillis?.()||0)<=7*86400000).length,complete=adminRows.reduce((n,r)=>n+totals(r).completed,0),sessions=adminRows.reduce((n,r)=>n+(r.sessions||0),0);$('admin-content').innerHTML=`<div class="account-metrics"><section><strong>${adminRows.length}</strong><span>profiles loaded${hasMore?' · more available':''}</span></section><section><strong>${active}</strong><span>active in the last 7 days</span></section><section><strong>${complete}</strong><span>missions completed</span></section><section><strong>${sessions}</strong><span>learning sessions started</span></section></div><section class="panel"><h2>Where learners are practising</h2><p class="muted">Completed missions / possible completions among the loaded profiles. Refresh to include recent activity.</p>${chapterRows()}</section><section class="panel"><h2>Learner profiles</h2><label>Find a learner<input id="learner-search" type="search" placeholder="Search nickname or email"></label><div class="account-table"><table><thead><tr><th>Learner</th><th>Gems</th><th>Level 1</th><th>Level 2</th><th>Level 3</th><th>Last active</th></tr></thead><tbody id="learner-rows"></tbody></table></div>${hasMore?'<button id="more-learners">Load next 100 profiles</button>':''}</section><p class="muted">A session starts when a verified learner opens or reloads the app. These are learning activity counts, not precise study time. Counts include the owner profile. No advertising trackers are used.</p>`;const fill=()=>{const term=$('learner-search').value.toLowerCase(),rows=adminRows.filter(r=>(r.nickname+' '+r.email).toLowerCase().includes(term));$('learner-rows').innerHTML=rows.map(r=>{const t=totals(r);return `<tr><td><strong>${esc(r.avatar)} ${esc(r.nickname)}</strong><small>${esc(r.email)}</small></td><td>${t.gems}</td>${t.levels.map((n,i)=>`<td>${n}/${[50,32,24][i]}</td>`).join('')}<td>${esc(r.lastActive?.toDate?.().toLocaleString()||'Just now')}</td></tr>`;}).join('')||'<tr><td colspan="6">No learners match yet. Registered learners appear after verifying their email and opening the app.</td></tr>';};$('learner-search').oninput=fill;fill();if($('more-learners'))$('more-learners').onclick=()=>loadAdmin();}
function render(){header();if(!ready||loading){shell('Opening your adventure','<section class="panel"><p role="status">Loading your personal progress…</p></section>');return;}if(user&&!user.emailVerified){verification();return;}if(user&&!row){shell('Your profile could not load',`<section class="panel"><p>${esc(saveError)}</p><button id="retry-profile">Retry loading</button><button id="logout">Log out</button>${messageBox()}</section>`);$('retry-profile').onclick=()=>session(auth.currentUser);$('logout').onclick=()=>signOut(auth);return;}const id=location.hash.slice(1);if(id==='admin'){if(user)admin();else renderLogin('admin');return;}if(id==='profile'){if(user)profile();else renderLogin('login');return;}if(['login','register','forgot'].includes(id)){if(user&&id!=='forgot')profile();else renderLogin(id);return;}originalRoute();if(user){if(CHAPTERS.includes(id)&&!pending.visited.includes(id)){pending.visited.push(id);timer=setTimeout(()=>flush().catch(()=>{}),300);}document.querySelectorAll('.foot').forEach(el=>{el.textContent=user?'Your progress is saved in your personal profile.':'Guest progress stays on this device.';});}}
window.Accounts={changed(){if(!user||!row||loading)return;pending=merge(pending,fromGame(window.MCBridge.export()));remember();clearTimeout(timer);timer=setTimeout(()=>flush().catch(()=>{}),300);},signedIn:()=>!!user,render};
window.route=render;window.onhashchange=render;
document.querySelector('.shell>aside').addEventListener('click',event=>{if(!ready||loading||(user&&(!user.emailVerified||!row))){event.preventDefault();event.stopImmediatePropagation();render();}},true);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&user&&row)flush().catch(()=>{});});
window.addEventListener('online',()=>{if(user&&row)flush().catch(()=>{});});
window.addEventListener('beforeunload',event=>{if(saveError){event.preventDefault();event.returnValue='';}});
if(enabled)onAuthStateChanged(auth,session);else render();
header();
