/* Small teaching steps shared by lessons, missions and printed answers. */
(function(){
const courses={
zero:[
['A letter is a number’s name','x is a label for a number we have not chosen yet. It is not a multiplication sign. If we choose x = 2, every x in our calculation means 2.','x = 2'],
['What does the little number mean?','The small raised number is called a power. 2³ means multiply three copies of 2. First 2 × 2 = 4. Then 4 × 2 = 8.','2³ = 2 × 2 × 2 = 8'],
['Go backwards one step','2² uses two copies, so it is 4. Going from 2³ to 2² divides the answer by 2. Going from 2² to 2¹ divides by 2 again.','8 ÷ 2 = 4; 4 ÷ 2 = 2'],
['Keep the same pattern','One more step takes the power from 1 to 0. Keep dividing by 2: 2 ÷ 2 = 1. That is why 2⁰ is 1, not 0.','2¹ = 2 → 2⁰ = 1'],
['Keep zero out of this rule','For any nonzero number, x⁰ = 1. Nonzero means any number except 0. We cannot use the divide-backwards pattern with zero, because division by zero is not allowed. We leave 0⁰ undefined here.','x ≠ 0 means “x is not zero”'],
['Now use it in an equation','An equation says two amounts are equal. In x⁰ + 4 = 5, replace x⁰ with 1. We get 1 + 4 = 5. Every nonzero x works; this question does not give just one x.','1 + 4 = 5 ✓'],
['Two powers, one unknown left','In 3x⁰ + 2y⁰ + z = 10, assume x and y are nonzero. 3x⁰ means 3 × x⁰. Replace each zero power with 1, then multiply.','3 × 1 + 2 × 1 + z = 10'],
['Find the missing amount','3 + 2 is 5, so 5 + z = 10. What must we add to 5 to reach 10? Another 5. Check by putting it back: 3 + 2 + 5 = 10.','z = 5; check: 10 = 10']
],
linear:[
['Give the mystery price a name','You buy a snack and a ₹5 drink for ₹12 altogether. Call the snack price x. x means the number of rupees we need to find.','snack + drink = whole bill'],
['Turn the story into maths','One snack costs x and the drink costs 5. Put them together with +. The equals sign means “has the same value as”.','x + 5 = 12'],
['Keep both sides fair','Imagine two balanced trays. If we take ₹5 from only one tray, they stop matching. Take ₹5 from BOTH sides to keep the equation true.','x + 5 − 5 = 12 − 5'],
['See what is left','On the left, adding 5 and taking 5 away cancel each other. Only x stays. On the right, 12 − 5 is 7. So the snack costs ₹7.','x = 7'],
['Always put the answer back','Try 7 in the original story: ₹7 for the snack plus ₹5 for the drink makes ₹12. It matches the bill, so our answer works.','7 + 5 = 12 ✓'],
['What does 3y mean?','3y is short for 3 × y, or y + y + y. It means three equal groups. Also, x¹ just means x: one copy of the number.','3y = y + y + y'],
['Use the information you are given','For 2x + 3y = 12, we are told x = 3. Replace x with 3. Then do the multiplication 2 × 3 first.','2 × 3 + 3y = 12 → 6 + 3y = 12'],
['Remove six from both sides','Take 6 away from each side. On the left that leaves three y groups. On the right, 12 − 6 leaves 6.','3y = 6'],
['Share to find one group','Three equal groups total 6. Divide both sides by 3 to find one group: y = 2. Check: 2 × 3 + 3 × 2 = 6 + 6 = 12.','y = 6 ÷ 3 = 2'],
['Why did we need x = 3?','Without that extra clue, several pairs work. x = 0 with y = 4 gives 12 too. One equation with two unknowns does not usually tell us one unique pair.','(x, y) = (3, 2) or (0, 4), and more']
],
square:[
['First, what does x² mean?','x is a number’s name. x² means x × x. It does not mean 2 × x. If x is 4, x² is 4 × 4 = 16.','x² = x × x'],
['Picture a square of tiles','A square with 4 rows and 4 tiles in each row has 16 tiles. This is why a square garden’s area is side × side. We measure area in square units.','4 rows × 4 tiles = 16 tiles'],
['Work backwards from sixteen','For x² = 16, ask: which number multiplied by itself gives 16? 4 does. So does −4, because a negative times a negative is positive. A real garden uses the positive length, 4.','4 × 4 = 16; (−4) × (−4) = 16'],
['What are we trying to change?','Now look at x² + 5x + 6. 5x means five copies of x. We want to write the SAME amount as a multiplication. This rewriting is called factoring. We are not solving for x yet.','x × x + 5 × x + 6'],
['Brackets keep a group together','(x + 2) means “work out x plus 2 as one group”. Two brackets side by side mean multiply the groups. For example, (4 + 2)(4 + 3) means 6 × 7.','(x + 2)(x + 3) means (x + 2) × (x + 3)','factor'],
['Split a rectangle into four parts','Imagine one side is x + 2 and the other is x + 3. Split each side at x. Every piece on one side must multiply every piece on the other. That makes four smaller rectangles. Tap each box to see its multiplication.','Four boxes: x × x, x × 3, 2 × x, 2 × 3','factor'],
['Count all four boxes','The boxes contain x², 3x, 2x and 6. Add them because together they fill the whole rectangle. 3x + 2x is five copies of x, just like 3 apples + 2 apples is 5 apples.','x² + 3x + 2x + 6 = x² + 5x + 6','factor'],
['But how did we choose 2 and 3?','We need two numbers whose product makes the last number, 6. Positive whole-number pairs are 1 and 6, or 2 and 3. We also need their sum to make the middle count, 5. Test both pairs below.','1 + 6 = 7 ✗; 2 + 3 = 5 ✓','pairs'],
['Now we can build the brackets','2 and 3 multiply to 6 AND add to 5. Put one in each bracket with x. Multiplying the four boxes gives our original expression, so the two ways of writing it are equal.','x² + 5x + 6 = (x + 2)(x + 3)','factor'],
['Check with an ordinary number','Try x = 4. The original gives 16 + 20 + 6 = 42. The brackets give (4 + 2)(4 + 3) = 6 × 7 = 42. This is a useful check. The four-box multiplication explains why it works for every x.','42 = 42 ✓'],
['When the product must be zero','Now solve x² + 5x + 6 = 0. We can write (x + 2)(x + 3) = 0. Two real numbers multiply to zero only if at least one of them is zero. For example, 0 × 9 = 0.','First group = 0 OR second group = 0'],
['Make the first group zero','Ask: what number plus 2 gives 0? −2. So x + 2 = 0 gives x = −2. Check in the original: (−2)² + 5(−2) + 6 = 4 − 10 + 6 = 0.','x = −2 ✓'],
['Make the second group zero','What number plus 3 gives 0? −3. Check: (−3)² + 5(−3) + 6 = 9 − 15 + 6 = 0. Both −2 and −3 work. These are algebra answers, not negative garden lengths.','x = −2 OR x = −3 ✓']
],
cube:[
['Build one layer first','A cube-shaped box has equal width, depth and height. If its side is 3 units, one layer holds 3 rows of 3 little cubes.','One layer: 3 × 3 = 9'],
['Stack the layers','The height is 3 units, so stack 3 layers. Each layer has 9 little cubes. Altogether we have 9 × 3 = 27.','3 × 3 × 3 = 27'],
['Use the short way to write it','x³ means x × x × x. For x³ = 27, try 3: 3 × 3 × 3 = 27. Trying −3 gives −27, so −3 is not an answer to this equation.','x³ = 27 → x = 3'],
['Look for the repeated piece','In x³ − 2x², write x³ as x² × x. Write 2x² as x² × 2. Both parts contain a copy of x².','x² × x − x² × 2'],
['Group the shared copies','Think of 5 bags of sweets minus 2 bags of the same sweets: (5 − 2) bags. Here our shared “bag” is x². Its number of copies is x − 2.','x² × (x − 2)'],
['Check by multiplying back','Multiply x² by each part inside the bracket. x² × x = x³. x² × (−2) = −2x². Adding those gives exactly what we started with.','x²(x − 2) = x³ − 2x²'],
['Make the product zero','For x²(x − 2) = 0, either x² must be 0 or x − 2 must be 0. Zero times any real number is zero.','x² = 0 OR x − 2 = 0'],
['Find and test both answers','x² = 0 gives x = 0. x − 2 = 0 gives x = 2. Check 0: 0 − 0 = 0. Check 2: 8 − 8 = 0. Do not divide by x²: it might be zero, and we would lose that answer.','x = 0 OR x = 2 ✓']
],
angles:[
['Find the hinge','An angle measures a TURN. The gate’s hinge is the vertex. One ray shows where the gate started; the other shows where it stopped. A ray is a line going out in one direction.','Angle = amount of turn'],
['Imagine a whole spin','A complete turn is split into 360 equal tiny turns called degrees. We write 360°. Half of that is 180°, and a quarter is 90°.','360 ÷ 4 = 90°'],
['Meet the small angles','No turn is 0°. A turn bigger than 0° but smaller than 90° is acute. Exactly 90° is a right angle, like the corner of a book. The small square mark means 90°.','0° < acute < 90°'],
['Open wider','More than 90° but less than 180° is obtuse. Exactly 180° is a straight angle: the two rays point in opposite directions.','90° < obtuse < 180°'],
['Go past a half turn','More than 180° but less than 360° is reflex. Follow the orange arc to see that larger turn. Exactly 360° is a full turn, ending in the starting direction.','180° < reflex < 360°'],
['Check what changes the angle','Make a ray longer in your mind. Its direction stays the same, so the angle stays the same. We measure the opening between directions, not the length of the arms.','Longer arms ≠ bigger angle']
],
draw:[
['Choose a target','Let’s draw 60°. It is smaller than a right angle, so we expect a fairly small opening. Predicting its size helps us spot a wrong scale later.','Target: 60°, less than 90°'],
['Start at the marked dot','The marked dot is the vertex. The blue baseline points right from it. On paper, use a ruler to draw this first ray.','Vertex → baseline'],
['Place the measuring tool','A protractor measures angles. Its centre must sit exactly on the vertex. Its straight edge must line up with the baseline. If either moves, the reading changes.','Centre on vertex; zero on baseline'],
['Read from the correct zero','Our baseline points right, so begin at the right-hand 0°. Move anticlockwise up to 60°. The opposite scale would read 120° at the same mark: that is the wrong scale for this baseline.','Start at 0°, then 30°, then 60°'],
['Mark, then connect','Tap the board to place the orange dot. On paper, mark a small dot at the degree you want. Connect that dot to the original vertex. The new ray gives the second direction.','Vertex → your mark'],
['Check before you finish','Press Check my drawing. A 60° angle should be smaller than a book’s 90° corner. If it looks wider than that, check your zero and scale. Try another target when you are ready.','Estimate first; measure to check']
],
missing:[
['Choose the total turn','First ask what shape the angles fill. A straight line is half a turn, or 180°. All the way around a point is a full turn, or 360°.','Half turn: 180° · full turn: 360°'],
['Find the space left on a line','One part is 110° and the other is x. Together they must fill 180°. Take the known 110° from the whole 180° to find the missing part.','x = 180° − 110° = 70°'],
['Check by adding back','Add the two parts: 110° + 70° = 180°. The total fits a straight line. That is our check.','110° + 70° = 180° ✓'],
['Add the known parts around a point','The known turns are 120° and 150°. Add those first: 120 + 150 = 270. The complete turn is 360°, so 360 − 270 = 90° is still missing.','120° + 150° + 90° = 360° ✓'],
['Why are opposite angles equal?','When two lines cross, a 45° angle and its neighbour make 180°. The neighbour is 135°. That same neighbour plus the angle opposite 45° also makes 180°, leaving 45° again.','180 − 45 = 135; 180 − 135 = 45'],
['Read 2x and 3x as copies','2x means two copies of x; 3x means three copies. On our line, 2x + 3x + 50° = 180°. Two copies and three copies make five copies.','5x + 50° = 180°'],
['Remove the known angle fairly','Subtract 50° from BOTH sides. That leaves five equal x parts on the left and 130° on the right.','5x = 180° − 50° = 130°'],
['Share the remaining turn','Divide 130° into 5 equal parts: 130 ÷ 5 = 26. So x = 26°. The labelled angles are 2x = 52° and 3x = 78°. Check: 52 + 78 + 50 = 180.','x = 26°; 52° + 78° + 50° = 180° ✓']
],
quads:[
['Connect four corners','A quadrilateral is a shape with four straight sides. Draw its corners in order around the edge. Do not cross the sides. The angles we want are INSIDE the shape.','Four sides · four inside angles'],
['Split the park into two triangles','Draw a diagonal: a line between opposite corners, inside the shape. It splits the park into two triangles. Each triangle’s inside angles total 180°.','180° + 180° = 360°'],
['A useful triangle check','Cut out a paper triangle. Tear off its three corners and place the vertices together without overlapping. The corners fit along a straight line, helping you see the 180° total.','Triangle corners make a half turn'],
['Square or rectangle?','Both have four 90° corners. Four times 90° is 360°. A square also has four equal sides. A rectangle can have a long side and a short side.','90° + 90° + 90° + 90° = 360°'],
['Opposite and neighbouring corners','Opposite means across the shape, not next door. In a parallelogram, opposite angles match. Neighbouring angles total 180° because the sides opposite them are parallel. So beside 65° comes 115°.','65° + 115° = 180°'],
['What makes a rhombus?','All four sides have equal length. Its opposite angles match, but its corners need not be right angles. A square is a special rhombus with four right angles.','Equal sides do not always mean 90° corners'],
['Look for the parallel pair','A trapezium, also called a trapezoid, has a pair of parallel sides. Parallel lines keep the same distance apart. The two inside angles along each joining leg total 180°.','One leg: 100° + 80° = 180°'],
['Look at a kite','A kite has two pairs of equal neighbouring sides. The angles between the unequal sides, across from each other, are equal. In our upright drawing these are the left and right corners.','Match sides first, then compare corners'],
['Find the unknown corner','The four angles are 100°, 100°, 80° and x. Add what we know: 100 + 100 + 80 = 280°. Take 280° away from the whole 360°.','x = 360° − 280° = 80°'],
['Check the whole shape','Put 80° back: 100 + 100 + 80 + 80 = 360°. In a shape with a dent, one inside angle can exceed 180°. The four inside angles still total 360° if the outline does not cross.','100° + 100° + 80° + 80° = 360° ✓']
]};
for(const c of L2_DATA.chapters)c.steps=courses[c.id];
L2_DATA.chapters.find(c=>c.id==='square').why='Area helps us plan gardens and count tiles. Building the same rectangle in two ways helps us understand where brackets come from.';
window.KidTutor={solution(steps){return '<div class="kid-solution"><p>Open each step in order. Take your time and check the last step.</p>'+steps.map((s,i)=>{const colon=s.indexOf(':');return `<details ${i===0?'open':''}><summary>Step ${i+1}${colon>0&&colon<45?' · '+s.slice(0,colon):''}</summary><p>${colon>0&&colon<45?s.slice(colon+1).trim():s}</p></details>`}).join('')+'</div>'},visual(kind){if(kind==='pairs')return `<div class="factor-discovery"><p>Which pair makes 6 when multiplied AND 5 when added?</p><button class="quiet" onclick="KidTutor.pair(1,6)">Try 1 and 6</button> <button class="quiet" onclick="KidTutor.pair(2,3)">Try 2 and 3</button><p id="pair-feedback" aria-live="polite">Test both pairs. A pair must pass both checks.</p></div>`;if(kind!=='factor')return '';return `<div class="factor-discovery"><p><strong>One rectangle. Four smaller parts.</strong><br>Side lengths: x + 2 and x + 3. Tap a box.</p><table class="factor-table"><caption>Multiply row × column. This is a multiplication map, not a scale drawing.</caption><thead><tr><th scope="col">×</th><th scope="col">x</th><th scope="col">3</th></tr></thead><tbody><tr><th scope="row">x</th><td><button onclick="KidTutor.box(0)">x²</button></td><td><button onclick="KidTutor.box(1)">3x</button></td></tr><tr><th scope="row">2</th><td><button onclick="KidTutor.box(2)">2x</button></td><td><button onclick="KidTutor.box(3)">6</button></td></tr></tbody></table><p id="box-feedback" aria-live="polite">The rectangle picture uses positive lengths. The multiplication rule also works for negative numbers.</p></div>`},box(i){document.getElementById('box-feedback').textContent=['Row x × column x = x × x = x². This is the large square.','Row x × column 3 = x × 3 = 3x. This is three copies of x.','Row 2 × column x = 2 × x = 2x. This is two copies of x.','Row 2 × column 3 = 2 × 3 = 6. These are six little unit squares.'][i]},pair(a,b){document.getElementById('pair-feedback').textContent=`${a} × ${b} = ${a*b}: product check passes. ${a} + ${b} = ${a+b}: ${a+b===5?'sum check passes too! Use 2 and 3 in the brackets.':'we need 5, so this pair does not fit the middle term.'}`}};
const lcmSteps=(a,b)=>{let m=a;while(m%b)m+=a;return [`Understand: We want the FIRST time two repeating patterns meet after the start. One repeats every ${a}; the other every ${b}.`,`List the first pattern: Keep adding ${a}. Its visits are ${Array.from({length:m/a},(_,i)=>(i+1)*a).join(', ')}. These are called multiples of ${a}.`,`List the second pattern: Keep adding ${b}. Its visits are ${Array.from({length:m/b},(_,i)=>(i+1)*b).join(', ')}.`,`Compare: ${m} is the first positive number in both lists. That makes it the least common multiple, or LCM. We do not count 0 because it is the starting meeting.`,`Check: ${m} ÷ ${a} = ${m/a} and ${m} ÷ ${b} = ${m/b}. Both patterns land exactly on ${m}, and no earlier positive visit appears in both lists.`]};
const factors=n=>Array.from({length:n},(_,i)=>i+1).filter(d=>n%d===0);
const hcfSteps=(a,b)=>{const common=factors(a).filter(d=>b%d===0),g=common.at(-1);return [`Understand: We want the biggest number that shares BOTH totals exactly. “Exactly” means nothing is left over. This is called the highest common factor, or HCF.`,`Try the first total: The numbers that divide ${a} exactly are ${factors(a).join(', ')}. These are its factors.`,`Try the second total: The numbers that divide ${b} exactly are ${factors(b).join(', ')}.`,`Choose: Both lists contain ${common.join(', ')}. The biggest shared number is ${g}. For packing, it gives ${g} identical groups.`,`Check: ${a} ÷ ${g} = ${a/g} and ${b} ÷ ${g} = ${b/g}. Each group gets ${a/g} of the first item and ${b/g} of the second. Multiplying by ${g} returns both original totals.`]};
const work=[];const set=(id,steps)=>work[id-1]=steps;
[[1,4,6],[2,3,5],[3,2,8],[4,6,9],[5,5,10],[7,8,12]].forEach(([id,a,b])=>set(id,lcmSteps(a,b)));
set(6,[...lcmSteps(4,6),'Connect to fractions: The denominator is the bottom number. It names how many equal pieces make a whole. We need a piece size both quarters and sixths can become.','Make the pieces match: Split each quarter into 3 smaller pieces: 1/4 = 3/12. Split each sixth into 2: 1/6 = 2/12. Both now count twelfths.']);
[[8,12,18],[9,8,12],[10,15,25],[11,12,18],[12,16,24],[13,7,9]].forEach(([id,a,b])=>set(id,hcfSteps(a,b)));
set(14,['Understand: 8/12 means 8 of 12 equal pieces. Simplest form means the same share written with the smallest possible whole-number top and bottom.','Find equal groups: The biggest number dividing both 8 and 12 is 4. Group the pieces in fours.','Count the groups: 8 ÷ 4 = 2 groups taken. 12 ÷ 4 = 3 groups in the whole. So the share is 2/3.','Why both numbers change: We changed how we count the pieces, not how much pizza we have. Dividing only one number would change the share.','Check: Multiply both numbers in 2/3 by 4 and you get 8/12 again. 2 and 3 have no shared factor bigger than 1.']);
set(15,['Understand: A fraction tells us how many equal pieces we take from one whole.','Count the whole: There are 4 equal slices altogether. Put 4 at the bottom; it tells us the size of the pieces.','Count what we take: We take 3 slices. Put 3 at the top. Our fraction is 3/4.','Check: We took 3 and left 1. Together that is 4 out of 4 slices, or one whole pizza.']);
set(16,['Picture it: Take half a pizza. Now cut BOTH halves into two equal pieces. The whole pizza now has 4 pieces.','Count your share: Your original half now contains 2 of the 4 pieces. You have not added or removed any pizza.','Write it: Multiply top and bottom by 2: (1 × 2)/(2 × 2) = 2/4.','Check: Two quarters cover exactly the same area as one half, so 1/2 = 2/4.']);
set(17,['Understand: Both fractions count sevenths: equal pieces of the same size. We can count them together.','Add the counts: 2 pieces plus 3 pieces makes 5 pieces.','Keep the size: The pieces are still sevenths, so the bottom stays 7. We get 5/7, not 5/14.','Check: Start with 5 sevenths and remove 3 sevenths. That leaves the original 2 sevenths.']);
set(18,['Understand: We are putting half a pizza and a quarter of a same-size pizza together. Halves and quarters are different-size pieces.','Make equal pieces: Cut the half into two quarters. That changes 1/2 into 2/4 without changing the amount.','Add: Two quarters plus one quarter makes three quarters: 2/4 + 1/4 = 3/4.','Check: 3/4 is more than 1/2 but less than a whole pizza. Removing the extra quarter leaves 2/4, which is the original half.']);
set(19,['Understand: We start with 5 sixths and take away 2 sixths. The piece sizes already match.','Subtract: 5 − 2 = 3, so 5/6 − 2/6 = 3/6. Keep the denominator 6 because the pieces are still sixths.','Simplify: Three pieces out of six equal pieces is half. Divide both numbers by 3: 3/6 = 1/2.','Check: Add the removed 2/6 back to 3/6. It returns 5/6.']);
set(20,['Understand: We must compare the same-size wholes using the same-size pieces. Comparing just the top numbers can mislead us.','Change quarters: Cut each quarter into 3 parts. 3/4 becomes 9/12 because 3 × 3 = 9 and 4 × 3 = 12.','Change thirds: Cut each third into 4 parts. 2/3 becomes 8/12.','Compare: Nine twelfths is one twelfth more than eight twelfths. So 3/4 is larger.','Check: The difference is 1/12, a small positive share, so these two fractions are close but not equal.']);
set(21,['Understand: Thirds and sixths are different-size pieces. Make them match before adding.','Split the third: Cut it into 2 equal pieces. One third becomes two sixths: 1/3 = 2/6.','Add the pieces: 2/6 + 1/6 = 3/6. The piece size stays one sixth.','Simplify and check: 3 is half of 6, so 3/6 = 1/2. Taking 1/6 back from 3/6 leaves 2/6, the original 1/3.']);
set(22,['Understand: 3/4 of 20 means split 20 apples into 4 equal groups, then choose 3 groups.','Find one group: 20 ÷ 4 = 5 apples in each quarter.','Take three groups: 5 + 5 + 5 = 15 apples. That is 3 × 5.','Check: The remaining group has 5 apples. Our 15 plus the remaining 5 returns all 20.']);
set(23,['Understand: Start with three quarters. We want to remove half of the same-size whole.','Match the pieces: One half is two quarters, so write 1/2 as 2/4.','Take away: 3 quarters minus 2 quarters leaves 1 quarter. So 3/4 − 1/2 = 1/4.','Check: The remaining 1/4 plus the removed 2/4 gives the starting 3/4.']);
set(24,['Understand: We add two milk amounts. Third-cups and quarter-cups are different sizes, so we need matching measuring pieces.','Find a shared size: 12 is a multiple of both 3 and 4. Use twelfths of a cup.','Convert each amount: 2/3 = (2 × 4)/(3 × 4) = 8/12. Also 1/4 = (1 × 3)/(4 × 3) = 3/12.','Add: 8 twelfths + 3 twelfths = 11 twelfths, or 11/12 cup.','Check: 11/12 − 3/12 = 8/12, which simplifies back to 2/3.']);
set(25,['Understand: 29 is a count of whole things. 1/5 is one small piece of another whole, split into five equal parts.','Keep both amounts: We have 29 wholes AND one fifth. That is written 29 1/5, a mixed number.','Count only fifths if you want: Each whole has 5 fifths. 29 wholes have 29 × 5 = 145 fifths. Add the extra one to get 146/5.','Check: 146 ÷ 5 gives 29 whole groups with 1 fifth left. This returns 29 1/5.']);
set(26,['Understand: 7 2/3 means seven whole pizzas and two extra third-slices. We want to count everything using thirds.','Count the wholes: Every whole has 3 thirds. Seven wholes have 7 × 3 = 21 thirds.','Add the extra pieces: 21 + 2 = 23 thirds. Write this as 23/3. The bottom stays 3 because the slice size did not change.','Check: 23 ÷ 3 gives 7 complete groups and 2 pieces left. That is 7 2/3 again.']);
set(27,['Understand: 17/4 means 17 quarter-pieces. Every 4 quarters makes one whole.','Make full groups: 4 + 4 + 4 + 4 = 16. We can make 4 wholes from 16 pieces.','Keep the leftover: 17 − 16 = 1 quarter remains. So the mixed number is 4 1/4.','Check: 4 wholes × 4 quarters + 1 quarter = 17 quarters, which is 17/4.']);
set(28,['Understand: We are adding two amounts: 6 whole things and 3 quarters, plus 2 whole things and 1 quarter.','Add the wholes: 6 + 2 = 8 wholes.','Add the pieces: 3/4 + 1/4 = 4/4. Four quarters make one whole.','Join them: 8 wholes plus the extra whole makes 9.','Check: 9 − 2 1/4 leaves 6 3/4, the first amount.']);
set(29,['Understand: We take 4 1/3 from 10 2/3. There are enough thirds to subtract without borrowing a whole.','Subtract the wholes: 10 − 4 = 6.','Subtract the pieces: 2/3 − 1/3 = 1/3. The pieces stay thirds.','Join and check: We get 6 1/3. Adding back 4 1/3 gives 10 2/3.']);
set(30,['Understand: Five wholes and one half must all be counted in halves.','Count the whole parts: Each whole has 2 halves, so five wholes contain 5 × 2 = 10 halves.','Include the extra half: 10 + 1 = 11 halves. Write 11/2.','Check: 11 halves make 5 full pairs with 1 half left, or 5 1/2.']);
set(31,['Understand: A decimal is another way to name a fraction. The second place after the point counts hundredths.','Use 100 pieces: Multiply top and bottom of 1/4 by 25. That gives 25/100 without changing its value.','Write hundredths: 25 hundredths is 0.25. In money, it is like 25 paise out of one rupee.','Check: Four lots of 0.25 make 1.00, just as four quarters make a whole.']);
set(32,['Understand: Compare the place values, not the number of digits. 0.5 means five tenths.','Make matching places: 0.5 = 0.50. Adding a zero at the end does not change its value.','Compare hundredths: 0.50 has 50 hundredths, 0.25 has 25, and 0.05 has 5. Fifty is the most.','Check: Half a rupee is 50 paise, more than 25 paise or 5 paise. So 0.5 is largest.']);
set(33,['Understand: We are adding two prices. Keep rupees with rupees and paise with paise.','Add the paise: 50 paise + 25 paise = 75 paise. This is 0.75 rupee.','Add the rupees: 2 + 1 = 3 rupees. Together the cost is ₹3.75.','Check: ₹3.75 − ₹1.25 = ₹2.50, the first price. When writing the sum, line up the decimal points.']);
set(34,['Understand: Two decimal places means keep two digits after the point. 7 2/3 means 7 + 2 ÷ 3.','See the repeating part: 2 ÷ 3 = 0.6666… . The 6 continues forever, so the exact number is 7.6666… .','Choose the nearest hundredth: The number is between 7.66 and 7.67. Its third decimal digit is 6, so it is nearer 7.67. Round the second decimal digit up.','Check: 7.67 is a rounded answer, not the exact fraction. Use ≈, meaning approximately equal: 7 2/3 ≈ 7.67.']);
set(35,['Understand: In 0.75, the 7 counts tenths and the 5 counts hundredths. Together that is 75 hundredths.','Write a fraction: 0.75 = 75/100.','Simplify: Divide both numbers by 25. 75 ÷ 25 = 3 and 100 ÷ 25 = 4, giving 3/4.','Check: Three quarters is 0.25 + 0.25 + 0.25 = 0.75.']);
set(36,['Understand: Change is the money left from your payment after the shop keeps the price.','Write matching places: ₹5 is ₹5.00. Subtract the cost ₹3.75.','Find the gap: From ₹3.75 to ₹4.00 is ₹0.25. From ₹4.00 to ₹5.00 is ₹1.00. Together the change is ₹1.25.','Check: Cost ₹3.75 + change ₹1.25 = payment ₹5.00.']);
const percent=(p,r)=>[ `Understand: ${r}% means ${r} out of every 100 equal parts of the price. First find the value of one part.`,`Find 1%: Divide ₹${p} by 100. Each 1% part is ₹${p/100}.`,`Find ${r}%: Take ${r} such parts: ₹${p/100} × ${r} = ₹${p*r/100}. This is the amount saved, not the amount paid.` ];
set(37,[...percent(200,10),'Check: Ten lots of ₹20 make ₹200, so ₹20 is one tenth, or 10%, of ₹200.']);
set(38,[...percent(200,25),'Answer the question: It asks how much you SAVE, so the answer is ₹50.','Check: ₹200 − ₹50 leaves ₹150 to pay. Saving plus payment, ₹50 + ₹150, returns the original ₹200.']);
set(39,[...percent(200,25),'Find the payment: Take the saving away from the original price: ₹200 − ₹50 = ₹150.','Check: ₹150 paid + ₹50 saved = ₹200. The question asks what you PAY, so choose ₹150.']);
set(40,[...percent(300,15),'Find the payment: ₹300 − ₹45 = ₹255. The discounted price is the price after the saving is removed.','Check: ₹255 paid + ₹45 saved = ₹300.']);
set(41,['Understand: There are two discounts, one after the other. The second acts on the price that is LEFT, not on the original price.','First saving: 10% of ₹100 is ₹10. Take it off: ₹100 − ₹10 = ₹90.','Second saving: Now find 10% of ₹90. ₹90 ÷ 10 = ₹9. Take that off: ₹90 − ₹9 = ₹81.','Check: Total saved is ₹10 + ₹9 = ₹19. ₹100 − ₹19 = ₹81. Adding 10% and 10% would use the wrong starting amount for the second discount.']);
set(42,['Understand: Interest is the EXTRA money earned. The original ₹1,000 is called the principal. We are asked only for the extra money.','Find the yearly extra: 10% means one tenth. ₹1,000 ÷ 10 = ₹100.','Use the time: This is one year, so the interest is one lot of ₹100.','Check: The total would be ₹1,000 + ₹100 = ₹1,100. But the question asks for interest only, so choose ₹100.']);
set(43,['Understand: Simple interest uses the ORIGINAL ₹1,000 every year. The question asks for the TOTAL, including that starting money.','Find one year: 10% of ₹1,000 is ₹100.','Count three years: ₹100 + ₹100 + ₹100 = ₹300 interest. The yearly amount stays the same.','Add the starting money: ₹1,000 + ₹300 = ₹1,300 total.','Check: Subtract the original ₹1,000 from ₹1,300 to get the ₹300 earned over the three years.']);
set(44,['Understand: Simple interest is calculated from the same starting ₹500 each year. We want the extra money after 2 years.','Find 1%: ₹500 ÷ 100 = ₹5. Then 8% is ₹5 × 8 = ₹40 for one year.','Count the years: Two equal yearly additions give ₹40 × 2 = ₹80 interest.','Check: The total is ₹580, but ₹580 − ₹500 = ₹80 is the INTEREST the question asks for.']);
set(45,['Understand: The rate is for a whole YEAR, but the money stays for only 6 months. We must use the same time unit.','Convert the time: A year has 12 months. Six months is 6/12 = 1/2 year.','Find the yearly extra: 10% of ₹1,000 is ₹100. Half a year earns half of that: ₹100 ÷ 2 = ₹50.','Check: Two six-month periods would earn ₹50 + ₹50 = ₹100, the full year’s simple interest.']);
set(46,['Understand: Compound interest adds the earned money into the balance. In the first year there is no earlier interest yet. We want the total.','Find the extra: 10% of ₹1,000 is ₹100.','Add it to the starting money: ₹1,000 + ₹100 = ₹1,100. This becomes the starting balance for year 2.','Check: The increase from ₹1,000 to ₹1,100 is ₹100, exactly 10% of the starting balance.']);
set(47,['Understand: YEAR 2 ALONE means only the new money earned in the second year, not all the interest so far.','Finish year 1: 10% of ₹1,000 is ₹100. The new balance is ₹1,100.','Use the new balance: For compound interest, year 2 earns on the entire ₹1,100. One tenth of ₹1,100 is ₹110.','Check: Of that ₹110, ₹100 comes from the original ₹1,000 and ₹10 comes from the earlier ₹100 interest. The year-2 interest is ₹110.']);
set(48,['Understand: Compound interest uses the growing balance. We need the TOTAL after both years.','Year 1: ₹1,000 earns ₹100, so the balance becomes ₹1,100.','Year 2: 10% of ₹1,100 is ₹110. Add it: ₹1,100 + ₹110 = ₹1,210.','Check: Starting money ₹1,000 + first interest ₹100 + second interest ₹110 = ₹1,210.']);
set(49,['Understand: Work through three years, always using the latest balance. At the end, remove the starting money to find interest ONLY.','Year 1: 10% of ₹200 is ₹20. New balance: ₹200 + ₹20 = ₹220.','Year 2: 10% of ₹220 is ₹22. New balance: ₹220 + ₹22 = ₹242.','Year 3: 10% of ₹242 is ₹24.20. New balance: ₹242 + ₹24.20 = ₹266.20.','Find the interest: ₹266.20 − original ₹200 = ₹66.20.','Check: The three extras also add to ₹20 + ₹22 + ₹24.20 = ₹66.20.']);
set(50,['Understand: “How much more” asks for the difference between two earnings over the SAME time. Both start with ₹1,000.','Simple interest: Each year earns 10% of the original ₹1,000, or ₹100. Two years give ₹200 interest and ₹1,200 total.','Compound interest: Year 1 earns ₹100, making ₹1,100. Year 2 earns 10% of ₹1,100, or ₹110. Total interest is ₹210 and total money is ₹1,210.','Compare: ₹210 − ₹200 = ₹10 more interest from compounding.','Check why: The first year’s extra ₹100 earns its own 10% in year 2. That extra ₹10 explains the difference.']);
questions.forEach((q,i)=>{if(!work[i])throw new Error('Missing Level 1 teaching: '+(i+1));q.steps=work[i];q.hint=work[i][1]});
// Reuse the full reasoning in tutorials, so worksheet answers and lessons agree.
const lessonMap={lcm:[1,2,6],hcf:[11,null,14],fractions:[15,18,22],mixed:[25,26,28],decimals:[31,33,34],discounts:[39,40,41],simple:[43,44,45],compound:[48,49,50]};
for(const [topic,ids] of Object.entries(lessonMap))ids.forEach((id,i)=>{if(id)lessons[topic][i][2]=work[id-1]});
lessons.hcf[1][2]=['Understand: Every pack must contain the same number of each kind of chocolate. We are trying 4 packs with 12 red and 18 yellow chocolates.','Share the red ones: 12 ÷ 4 = 3 in each pack. All 12 are used.','Share the yellow ones: Give 4 to each pack. That uses 4 × 4 = 16 and leaves 18 − 16 = 2 yellow chocolates.','Decide: The packs cannot use everything equally with 4 packs. Try 6 packs instead: 12 ÷ 6 = 2 red and 18 ÷ 6 = 3 yellow in each.','Check: Six lots of 2 red is 12, and six lots of 3 yellow is 18. Nothing is left.'];
lessons.fractions[1][2]=[...work[17],...work[18],...work[19]];
lessons.mixed[1][2]=[...work[25],...work[33]];
lessons.mixed[2][2]=[...work[27],...work[28]];
lessons.decimals[1][2]=[...work[32],...work[35]];
const take=(id,indices)=>indices.map(i=>courses[id][i][0]+': '+courses[id][i][1]);
const second=[
['Understand: x is given as 7. We are finding 7⁰, not 7 × 0.',...take('zero',[2,3]),'Use the rule: 7 is nonzero, so 7⁰ = 1.','Check: 7¹ = 7. Dividing by 7 once more gives 7⁰ = 1.'],
[...take('zero',[4,5]),'Try two checks: x = 2 gives 1 + 4 = 5. x = −3 also gives 1 + 4 = 5. So the answer is every nonzero real x.'],
['Understand: We need z, the missing number. The question says x and y are nonzero.',...take('zero',[6,7]),'Check the original: 3 × 1 + 2 × 1 + 5 = 3 + 2 + 5 = 10.'],
['Remember the rule: A NONZERO number to power zero is 1. That word matters.',...take('zero',[4]),'Choose: In this course we leave 0⁰ undefined. It is not covered by our rule.','Check your reasoning: We cannot explain it by 0 ÷ 0, because division by zero is not allowed.'],
take('linear',[0,1,2,3,4]),
['Read the equation: 3x = 18 means three equal copies of x make 18.','Picture it: Three bags contain the same number of marbles. Together they hold 18.','Find one bag: Share 18 into 3 equal groups: 18 ÷ 3 = 6. Dividing both sides of 3x = 18 by 3 leaves x = 6.','Check: 3 × 6 = 18, so x = 6 works.'],
take('linear',[5,6,7,8]),
['Understand: A unique pair means just one possible x and y together. We have not been told either value.','Try one pair: x = 3 and y = 2 gives 2 × 3 + 3 × 2 = 6 + 6 = 12.','Try another pair: x = 0 and y = 4 gives 2 × 0 + 3 × 4 = 0 + 12 = 12.','Conclude: Both pairs work, so this equation alone does not pick one unique pair. There are many possible pairs.'],
[...take('square',[0,2]),'Check the positive answer: 4 × 4 = 16.','Check the negative answer: (−4) × (−4) = 16. The question asks for ALL real solutions, so include both 4 and −4.'],
['Understand: A square’s area equals side × side. Call its side length x metres. We need x² = 25.','Try whole-number sides: 4 × 4 = 16 is too small. 5 × 5 = 25 fits.','Use the story: Algebra also allows −5, but a physical length cannot be negative. Choose 5 m for the garden.','Check the units: 5 m × 5 m = 25 m². A length is measured in metres, while the area uses square metres.'],
take('square',[3,4,5,6,7,8,9]),
take('square',[3,4,5,6,7,8,10,11,12]),
[...take('cube',[0,1,2]),'Check: 3 × 3 × 3 = 27. Unlike a square, cubing a negative stays negative, so −3 does not solve this positive equation.'],
['Understand: Volume counts how many unit cubes fill the space. A 4 cm cube has width, depth and height all equal to 4 cm.','Build one layer: 4 rows with 4 cubes in each row makes 4 × 4 = 16 unit cubes.','Stack four layers: 16 × 4 = 64 unit cubes. The volume is 64 cm³.','Check: The three dimensions give 4 cm × 4 cm × 4 cm = 64 cm³. Multiplying only two sides would give area, not volume.'],
take('cube',[3,4,5]),
take('cube',[3,4,5,6,7]),
['Understand: We are naming the size of a turn. Compare 65° with a right angle, which is 90°.','Compare: 65° is greater than 0° but less than 90°. It has not reached a quarter turn.','Name it: That range is called acute.','Check: It cannot be obtuse because obtuse angles are greater than 90°.'],
['Understand: The marked turn is 240°. Compare it with a half turn and a full turn.','Compare: 240° is more than 180° but less than 360°.','Name it: A turn in that range is reflex.','Check: 240° needs 120° more to complete 360°. It has already gone past a straight angle.'],
['Understand: One full turn contains 360°. A quarter means one of 4 equal parts.','Share the turn: Divide 360 by 4. 360 ÷ 4 = 90.','Answer: A quarter turn is 90°, which is a right angle.','Check: Four 90° turns add up to 360°, bringing you back to the start.'],
['Understand: An angle measures the turn between two directions.','Imagine longer rays: Extend both lines without turning either one. Their directions still match their original directions.','Find the change: No turning happened, so the angle changed by 0°.','Check: A small book and a big book can both have 90° corners even though their edges have different lengths.'],
[...take('draw',[1,2,3]),'Check: The centre of the protractor sits on the vertex, and the correct 0° sits on the baseline. Both alignments must be correct.'],
['Find the starting ray: The baseline points to the right. This is where the turn begins.','Match its zero: Start at the right-hand 0° on the protractor.','Follow that scale: Count anticlockwise from 0°, not from the numbers that begin on the left.','Check: Before making any turn, the baseline must read 0°. If your scale reads 180° there, you chose the wrong scale.'],
['Understand: Many protractors print two scales running in opposite directions.','Compare the readings: At one mark, a scale can show 60° while the other shows 120°. They add to 180°.','Find the likely mistake: Reading from the opposite zero gives the wrong scale’s 120° instead of 60°.','Check visually: 60° is smaller than a 90° corner. 120° is bigger. The size of the opening helps catch the mistake.'],
['Start with what is drawn: We already have a baseline and a mark at 60°.','Find the common starting point: Both rays must start at the vertex.','Connect: Use a straight line from the vertex through the new mark. This makes the second ray.','Check: The two rays now meet at the original vertex, and the opening between them is 60°.'],
take('missing',[0,1,2]),
['Choose the whole: These angles go all the way around a point, so their total is 360°.','Add what is known: 120° + 150° = 270°.','Find the space left: 360° − 270° = 90°, so x = 90°.','Check: 120° + 150° + 90° = 360°.'],
[...take('missing',[4]),'Answer: The vertically opposite angle is 45°. It is across the crossing, not next to the given angle.','Check: The four turns are 45°, 135°, 45°, 135°. Together they make 360°.'],
take('missing',[5,6,7]),
take('quads',[0,1,8,9]),
['Understand: Neighbouring angles are next to each other, sharing a side. In a parallelogram those inside angles add to 180°.','Write the total: 65° + x = 180°. We want the missing neighbour, not the opposite angle.','Subtract: x = 180° − 65° = 115°.','Check: 65° + 115° = 180°. The angle opposite 65° would instead be 65°.'],
[...take('quads',[5]),'Choose the always-true statement: All four sides are equal. Some rhombuses have sloping corners; a square has four 90° corners.','Check: Both a square and a sloping rhombus fit the equal-side rule. That means the rule works for both examples.'],
[...take('quads',[0,1,2]),'Conclude: Two triangles contribute 180° each. Together the quadrilateral’s interior angles total 360°. It does not need four right angles or four equal sides.']
];
L2_DATA.questions.forEach((q,i)=>{if(!second[i])throw new Error('Missing Level 2 teaching: '+(i+1));q.steps=second[i]});
})();
