const stories={
 lcm:['The birthday bus stop','At 9 o’clock, the park shuttle and the party bus arrive together. One returns every 4 minutes, the other every 6. When can the friends travel together again?','town'],
 hcf:['A gift for every friend','Vetri and Amma have 12 strawberry sweets and 18 caramel sweets. Make as many identical party boxes as possible. Every box needs both flavours, and nothing can be left over.','party'],
 fractions:['Save some pizza for your friends','The pizzas are the same size. Tap the slices you want to share. A fraction tells us how many equal pieces we have, and how many make a whole pizza.','pizza'],
 mixed:['How much pizza is on the table?','Two full pizzas and a few extra slices are waiting for the guests. Count everything in slices, then say the same amount using whole pizzas.','pizza'],
 decimals:['Count the coins at the shop','Vetri is checking his change. One rupee contains 100 paise. Collect the coins and watch the same amount become a fraction and a decimal.','town'],
 discounts:['Buy a birthday backpack','The shopkeeper has put a sale sticker on a backpack. Find the money you save first. The rest is what you actually pay.','town'],
 simple:['Save for next year’s celebration','Amma explains an imaginary savings plan: your starting money earns the same extra amount every year. Step through the years and watch the savings jar fill.','savings'],
 compound:['Let your savings earn too','In this imaginary plan, leave the extra money in your savings. Next year it earns interest as well. Compare this with earning only on the starting amount.','savings']
};
function scene(id,compact=false){const s=stories[id];return `<section class="story ${compact?'compact':''}"><div class="story-art ${s[2]}" role="img" aria-label="${{party:'Vetri and his mother packing birthday treats',pizza:'Friends sharing pizza at a garden birthday party',town:'Vetri shopping with his father in the neighbourhood',savings:'Vetri and his mother exploring savings jars'}[s[2]]}"></div><div class="story-caption"><p class="eyebrow">VETRI’S BIRTHDAY ADVENTURE</p><h2>${s[0]}</h2><p>${s[1]}</p></div></section>`}
const originalLesson=lesson,originalQuiz=quiz,originalLab=lab,originalRefresh=refreshLab;
lesson=function(id){originalLesson(id);main.querySelector('.tabs').insertAdjacentHTML('beforebegin',scene(id))};
quiz=function(){originalQuiz();main.querySelector('.lesson-grid').insertAdjacentHTML('beforebegin',scene(questions[quizIndex].topic,true))};
home=function(){current='world';nav();main.innerHTML=`<p class="eyebrow">A STORY YOU CAN PLAY</p><h1>Let’s plan a birthday!</h1><p class="muted">Catch the bus. Pack the treats. Share the pizza. Use maths to make the day happen.</p><div class="adventure-grid">${topics.map((t,i)=>`<a class="adventure-card" href="#${t[0]}"><div class="story-art ${stories[t[0]][2]}"></div><div><span class="eyebrow">CHAPTER ${i+1} · ${t[1]}</span><h2>${stories[t[0]][0]}</h2><p>${stories[t[0]][1]}</p><strong>${progress.lessons[t[0]]?'✓ Revisit the story':'Play this chapter →'}</strong></div></a>`).join('')}</div><div class="panel"><h2>Ready for a mission?</h2><p>Try 50 questions, with hints and a tutor who explains every answer.</p><button class="primary" onclick="openQuiz()">Start the quest challenge</button></div>`};
let storyStep=0;
lab=function(id){storyStep=0;if(!['hcf','lcm','fractions','mixed','decimals','simple','compound'].includes(id)){originalLab(id);return}let controls='';if(id==='hcf')controls=numeric('a','Strawberry sweets',12,1,24)+numeric('b','Caramel sweets',18,1,24)+numeric('packs','Party boxes',6,1,12);if(id==='lcm')controls=numeric('a','Shuttle: minutes between trips',4,1,12)+numeric('b','Party bus: minutes between trips',6,1,12);if(id==='fractions')controls=`<label>Equal slices in this pizza<select id="slices" onchange="storyStep=0;refreshLab()">${[2,3,4,6,8,12].map(x=>`<option ${x===4?'selected':''}>${x}</option>`).join('')}</select></label><button class="quiet" onclick="originalLab('fractions')">Explore adding and comparing →</button>`;if(id==='mixed')controls=numeric('whole','Whole pizzas',2,0,4)+numeric('a','Extra slices',3,0,7)+numeric('b','Slices in each pizza',4,2,8);if(id==='decimals')controls=`<label>Paise collected<input id="hundred" type="range" value="25" min="0" max="100" oninput="refreshLab()"></label>`;if(['simple','compound'].includes(id))controls=numeric('principal','Starting savings (₹)',1000,0,10000,10)+numeric('rate','Extra each year (%)',10,0,50);document.getElementById('lab').innerHTML=`<div class="controls">${controls}</div><div id="lab-result" aria-live="polite"></div>`;refreshLab()};
function sweets(n,kind){return Array.from({length:n},()=>`<span class="sweet ${kind}" aria-hidden="true"></span>`).join('')}
function pizza(n,d,interactive=false){return `<svg class="real-pizza" viewBox="0 0 220 220" role="${interactive?'group':'img'}" aria-label="${n} of ${d} equal pizza slices ${interactive?'selected':'remaining'}"><circle cx="110" cy="110" r="102" fill="#be7737"/>${Array.from({length:d},(_,i)=>{let a=i*2*Math.PI/d-Math.PI/2,b=(i+1)*2*Math.PI/d-Math.PI/2,x=110+95*Math.cos(a),y=110+95*Math.sin(a),xx=110+95*Math.cos(b),yy=110+95*Math.sin(b),mid=(a+b)/2;return `<g ${interactive?`role="button" tabindex="0" aria-label="Share ${i+1} of ${d} slices" onclick="storyStep=${i+1};refreshLab()" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();storyStep=${i+1};refreshLab()}"`:''}><path d="M110 110 L${x} ${y} A95 95 0 ${d===1?1:0} 1 ${xx} ${yy} Z" fill="${i<n?'#f6c45f':'#f0e4d0'}" stroke="#fff8eb" stroke-width="3"/>${i<n?`<circle cx="${110+58*Math.cos(mid)}" cy="${110+58*Math.sin(mid)}" r="9" fill="#c74735"/><circle cx="${110+76*Math.cos(mid+.13)}" cy="${110+76*Math.sin(mid+.13)}" r="4" fill="#568242"/>`:''}</g>`}).join('')}</svg>`}
refreshLab=function(){const id=current;let html='';if(id==='hcf'){let a=val('a'),b=val('b'),p=val('packs'),ar=Math.floor(a/p),br=Math.floor(b/p);storyStep=Math.min(storyStep,Math.max(ar,br));let ra=Math.min(storyStep,ar),rb=Math.min(storyStep,br),leftA=a-ra*p,leftB=b-rb*p;html=`<p><strong>Your mission:</strong> give each box the same treats. Each round puts one sweet of each available flavour into every box.</p><div class="sweet-key"><span class="sweet red"></span> Strawberry <span class="sweet gold"></span> Caramel</div><div class="supply-tray"><strong>Still on the table: ${leftA} strawberry + ${leftB} caramel</strong><div>${sweets(leftA,'red')}${sweets(leftB,'gold')}</div></div><div class="gift-grid">${Array.from({length:p},(_,i)=>`<div class="gift"><span>FRIEND ${i+1}</span><div>${sweets(ra,'red')}${sweets(rb,'gold')}</div><small>${ra} strawberry · ${rb} caramel</small></div>`).join('')}</div><div class="actions"><button class="primary" onclick="storyStep++;refreshLab()" ${storyStep>=Math.max(ar,br)?'disabled':''}>Deal one round</button><button class="secondary" onclick="storyStep=${Math.max(ar,br)};refreshLab()">Fill the boxes</button><button class="quiet" onclick="storyStep=0;refreshLab()">Empty boxes</button></div><div class="result">${storyStep<Math.max(ar,br)?'Keep packing — make every box match.':leftA||leftB?`These ${p} boxes leave ${leftA+leftB} sweets. Try a different box count.`:p===gcd(a,b)?`You did it! ${p} is the greatest number of equal boxes.`:`Nothing left! Can you make more than ${p} identical boxes?`}</div><details><summary>Explain the maths</summary><p>A box count must divide both ${a} and ${b} with no remainder. Their common factors are ${Array.from({length:Math.min(a,b)},(_,i)=>i+1).filter(n=>a%n===0&&b%n===0).join(', ')}. The greatest is ${gcd(a,b)}: the HCF.</p></details>`}
else if(id==='fractions'&&document.getElementById('slices')){let d=Number(document.getElementById('slices').value);storyStep=Math.min(storyStep,d);html=`<p>Tap a slice to share that many pieces, counting clockwise from the top.</p>${pizza(storyStep,d,true)}<div class="result">Sharing ${storyStep}/${d} of one pizza</div><p><strong>${storyStep}</strong> counts the slices you share. <strong>${d}</strong> counts all the equal slices in a whole pizza.</p><p>${d-storyStep} slices stay on the table. ${storyStep}/${d} + ${d-storyStep}/${d} = ${d}/${d} = 1 whole.</p><button class="quiet" onclick="storyStep=0;refreshLab()">Start again</button>`}
else if(id==='mixed'){let w=val('whole'),d=val('b'),a=Math.min(val('a'),d-1);document.getElementById('a').value=a;html=`<div class="pizza-table">${Array.from({length:w},()=>pizza(d,d)).join('')}${pizza(a,d)}</div><p>${w} whole pizzas give us ${w} × ${d} = ${w*d} slices. Add the ${a} extra slices.</p><div class="result">${w} ${a}/${d} = ${w*d+a}/${d}</div><p>Same food, two ways of counting: whole pizzas and a part, or all the slices together.</p>`}
else if(id==='lcm'){let a=val('a'),b=val('b'),m=lcm(a,b);storyStep=Math.min(storyStep,m);html=`<div class="station-clock">${9+Math.floor(storyStep/60)}:${String(storyStep%60).padStart(2,'0')} <small>${storyStep>=60?`(${storyStep} minutes after 9:00)`:''}</small></div><div class="bus-lane"><span class="bus ${storyStep%a===0?'arrived':''}">▣ SHUTTLE</span><strong>${storyStep%a===0?'At the stop!':`Back in ${a-storyStep%a} min`}</strong></div><div class="bus-lane"><span class="bus orange ${storyStep%b===0?'arrived':''}">▣ PARTY BUS</span><strong>${storyStep%b===0?'At the stop!':`Back in ${b-storyStep%b} min`}</strong></div><div class="actions"><button class="primary" onclick="storyStep++;refreshLab()" ${storyStep===m?'disabled':''}>Wait 1 minute →</button><button class="quiet" onclick="storyStep=0;refreshLab()">Back to 9:00</button></div><div class="result">${storyStep===0?'Both start together. When will they meet again?':storyStep===m?`Both here! The first meeting is after ${m} minutes.`:'Watch each bus follow its own timetable.'}</div><p>Shuttle visits: ${Array.from({length:Math.floor(storyStep/a)+1},(_,i)=>i*a).join(', ')} min.<br>Party bus visits: ${Array.from({length:Math.floor(storyStep/b)+1},(_,i)=>i*b).join(', ')} min.</p><details><summary>Why is this LCM?</summary><p>Each timetable counts multiples. The first positive time in both lists is their least common multiple: ${m}.</p></details>`}
else if(id==='decimals'){let h=val('hundred');html=`<p>Each copper coin stands for 1 paise. Ten make one row; 100 make ₹1.</p><div class="coin-tray">${Array.from({length:100},(_,i)=>`<span class="coin ${i<h?'collected':''}">${i<h?'1':''}</span>`).join('')}</div><div class="result">${h} paise = ${h}/100 rupee = ₹${(h/100).toFixed(2)}</div><p>${Math.floor(h/10)} complete rows of ten, and ${h%10} extra coins. The two places after the decimal count tenths and hundredths of a rupee.</p>`}
else if(['simple','compound'].includes(id)&&!document.getElementById('years')){let p=val('principal'),r=val('rate'),compound=id==='compound',balance=compound?p*(1+r/100)**storyStep:p*(1+r*storyStep/100),before=compound?p*(1+r/100)**Math.max(0,storyStep-1):p;html=`<p>Imagine a fixed ${r}% annual rate. Step forward one year at a time.</p><div class="savings-display"><div class="savings-jar"><div style="height:${Math.min(95,25+(p?((balance-p)/p)*35:0))}%"></div><strong>${money(balance)}</strong></div><div><h3>Year ${storyStep}</h3><p>Started with ${money(p)}</p><p>Extra earned: <strong>${money(balance-p)}</strong></p></div></div><div class="actions"><button class="primary" onclick="storyStep++;refreshLab()" ${storyStep===5?'disabled':''}>Let one year pass →</button><button class="quiet" onclick="storyStep=0;refreshLab()">Start again</button></div><div class="result">${storyStep?`This year: ${money(before)} × ${r}/100 = ${money(before*r/100)} extra`:'The jar contains only your starting money.'}</div><p>${compound?'The previous balance earns interest, including earlier interest.':'Only the original amount earns interest, so the yearly addition stays the same.'}</p><p>After ${storyStep} years: simple ${money(p*(1+r*storyStep/100))} · compound ${money(p*(1+r/100)**storyStep)}.</p><small>Learning example with annual compounding; amounts displayed to the nearest paise.</small>`}
else {originalRefresh();if(id==='discounts')document.getElementById('lab-result').insertAdjacentHTML('afterbegin',`<div class="shopping-item" style="display:flex;gap:20px;align-items:center"><svg width="100" height="120" viewBox="0 0 100 120" role="img" aria-label="Blue birthday backpack"><path d="M35 25V15Q50 0 65 15V25" fill="none" stroke="#294d69" stroke-width="8"/><rect x="15" y="22" width="70" height="88" rx="22" fill="#4d89a4"/><rect x="25" y="67" width="50" height="33" rx="8" fill="#2a617b"/><path d="M29 76h42" stroke="#e7ca85" stroke-width="3"/></svg><div><strong>Your birthday backpack</strong><p>Price tag: ${money(val('principal'))}<br>Sale sticker: ${val('rate')}% off</p></div></div>`);return}document.getElementById('lab-result').innerHTML=html};

route();
