const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const mathBox={};vm.createContext(mathBox);vm.runInContext(fs.readFileSync('level2-math.js','utf8'),mathBox);const M=mathBox.L2Math;
assert.equal(M.power(0,0),null);for(const x of [-6,-1,1,2,6])assert.equal(M.power(x,0),1);
for(let x=-12;x<=12;x++){assert.equal(M.power(x,1),x);assert.equal(M.power(x,2),x*x);assert.equal(M.power(x,3),x*x*x);assert(x*x+5*x+6===(x+2)*(x+3));assert(x*x*x-2*x*x===x*x*(x-2))}
assert.deepEqual([-4,4].map(x=>x*x),[16,16]);assert.deepEqual([-3,-2].map(x=>x*x+5*x+6),[0,0]);assert.deepEqual([0,2].map(x=>x**3-2*x*x),[0,0]);
assert.deepEqual([0,1,89,90,91,179,180,181,359,360].map(M.angleType),['Zero angle','Acute','Acute','Right','Obtuse','Obtuse','Straight','Reflex','Reflex','Full turn']);
for(let k=10;k<=170;k++){assert.equal(M.missing('line',k)+k,180);assert.equal(M.missing('cross',k),k);assert(Math.abs(5*M.missing('algebra',k)+k-180)<1e-9)}for(let k=10;k<=230;k++)assert.equal(120+k+M.missing('point',k),360);
assert.deepEqual([...M.polygon([[0,0],[100,0],[100,100],[0,100]])],[90,90,90,90]);assert.equal(M.polygon([[0,0],[100,100],[100,0],[0,100]]),null);assert.equal(M.polygon([[0,0],[0,0],[100,100],[0,100]]),null);assert.equal(M.polygon([[0,0],[100,0],[200,0],[300,0]]),null);
for(const points of [[[0,0],[200,0],[80,70],[0,200]],[[0,0],[200,0],[160,160],[-40,160]],[[0,0],[200,0],[250,150],[-50,150]]]){const a=M.polygon(points);assert(a);assert(Math.abs(a.reduce((s,n)=>s+n,0)-360)<1e-9);const reversed=M.polygon([...points].reverse());assert(Math.abs(reversed.reduce((s,n)=>s+n,0)-360)<1e-9)}
const box={window:{}};vm.createContext(box);vm.runInContext(fs.readFileSync('level2-data.js','utf8').replaceAll('L2_DATA.questions','window.L2_DATA.questions'),box);const D=box.window.L2_DATA;assert.equal(D.chapters.length,8);assert.equal(D.questions.length,32);assert.equal(new Set(D.chapters.map(c=>c.id)).size,8);D.questions.forEach(q=>{assert(D.chapters.some(c=>c.id===q.topic));assert.equal(q.options.length,4);assert.equal(new Set(q.options).size,4);assert.equal(q.options.filter(o=>o===q.answer).length,1);assert(q.steps.length>0)});
const answers=['1','Every nonzero real x','5','Undefined','₹7','6','2','No, many pairs work','4 and −4','5 m','(x + 2)(x + 3)','−2 and −3','3','64 cm³','x²(x − 2)','0 and 2','Acute','Reflex','90°','0°','On the vertex','The right-hand 0°','You read the opposite scale','Connect the vertex to the mark','70°','90°','45°','26°','80°','115°','All four sides are equal','It splits into two triangles'];D.questions.forEach((q,i)=>assert.equal(q.answer,answers[i]));
console.log('PASS: powers and factor identities; angle boundaries; every missing-angle slider value; convex/concave/crossing polygon calculations; 8 chapters and all 32 mission answers.');
