const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');let elements={};function el(id){return elements[id]||(elements[id]={value:'',textContent:'',max:6,get innerHTML(){return this.html||''},set innerHTML(s){this.html=s;for(const m of s.matchAll(/id="(v-[^"]+)"[^>]*value="([^"]+)"/g))el(m[1]).value=m[2];if(s.includes('id="v-target"'))el('v-target').value='64'},insertAdjacentHTML(_,s){this.html=(this.html||'')+s},querySelector(){return null}})}
const b={console,Math,setInterval,clearInterval,location:{hash:''},localStorage:{getItem:()=>null,setItem(){}},document:{getElementById:el,querySelector:el},main:el('main'),current:'',route(){},money:n=>'₹'+n.toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2}),KidTutor:{solution:a=>a.join(' ')},speechSynthesis:{cancel(){}},scrollTo(){}};b.window=b;vm.createContext(b);vm.runInContext(fs.readFileSync('level3-data.js','utf8'),b);vm.runInContext(fs.readFileSync('level3.js','utf8').replace(/route\(\);\s*\}\)\(\);\s*$/,'})();'),b);
assert.equal(b.L3_DATA.chapters.length,6);assert.equal(b.L3_DATA.questions.length,24);const expected=['−1/2','−1/4','3/2','0','₹6','4','4','9','70°','Every square is a rectangle','115°','They cut each other in half','8','7 and 8','6','9 m','4','5 units','−3','6','₹170','₹187','25%','40%'];b.L3_DATA.questions.forEach((q,i)=>{assert.equal(q.answer,expected[i]);assert.equal(new Set(q.options).size,4);assert(q.steps.length>=3)});
function open(id){b.location.hash='#l3-'+id;b.route()}
for(const c of b.L3_DATA.chapters){open(c.id);assert(el('l3-picture').innerHTML.length>100);assert(!el('l3-result').innerHTML.includes('NaN'))}
open('cuberoots');for(let side=1;side<=6;side++)for(let layers=1;layers<=side;layers++){el('v-side').value=side;el('v-layers').value=layers;el('v-turn').value=45;b.L3.change();const pic=el('l3-picture').innerHTML;assert.equal((pic.match(/<polygon/g)||[]).length,3*side*side*layers);assert(pic.includes(`${side} × ${side} × ${layers} = ${side*side*layers}`));assert(el('l3-result').innerHTML.includes(`∛${side**3} = ${side}`))}
open('linear');el('v-x').value=6;b.L3.change();assert(el('l3-result').innerHTML.includes('Balanced!'));
open('roots');el('v-side').value=8;b.L3.change();assert(el('l3-result').innerHTML.includes('√64 = 8'));el('v-target').value=50;b.L3.change();assert(el('l3-result').innerHTML.includes('between 7 and 8'));
open('compare');assert(el('l3-picture').innerHTML.includes('₹187.00'));open('rational');assert(el('l3-result').innerHTML.includes('= -1/4'));
b.location.hash='#l3-quests';b.route();b.L3.filter('roots');assert.equal((el('main').innerHTML.match(/aria-label="Mission/g)||[]).length,4);for(let i=0;i<5;i++)b.L3.nextQuestion();assert(el('main').innerHTML.includes('Squares and square roots'));
console.log('PASS: all 24 mission answers; six working experiments; 21 complete/partial cube counts; square-root bounds; ticket balance; discount-plus-tax; rational addition; chapter filtering and next-mission wrapping.');
